basePath: /
host: exz4e5um5a.eu-central-1.awsapprunner.com
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Calculate number of packs that needed to be shipped.
  title: Gymshark Shipment Calculator API
  version: "1.0"
paths:
  /calculate/{itemCount}:
    get:
      parameters:
      - description: Item Count
        in: path
        name: itemCount
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Calculate item packs
swagger: "2.0"
