name: GitHub Actions ECR Push
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Build Docker image
      run: docker build --platform=linux/amd64 -t gymshark-shipment-calculator-api:v1 .

    - name: Push to ECR
      id: ecr
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: eu-central-1
        local-image: gymshark-shipment-calculator-api:v1
        image: gymshark-shipment-calculator-api:v1, gymshark-shipment-calculator-api:latest

